# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Arduino Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  arduino-lint:
    name: Arduino Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2
        with:
          library-manager: update
