name: Async TCP CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  arduino:
    name: ${{ matrix.config }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [arduino-cli.yaml, arduino-cli-dev.yaml]
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v1
      - name: Download board
        run: |
          arduino-cli --config-file ${{ matrix.config }} core update-index
          arduino-cli --config-file ${{ matrix.config }} board listall
          arduino-cli --config-file ${{ matrix.config }} core install esp32:esp32

      - name: Client
        run: arduino-cli --config-file ${{ matrix.config }} --library ./src/ compile --fqbn esp32:esp32:esp32 ./examples/Client/Client.ino

      - name: Client IPv6
        env:
          LWIP_IPV6: true
        run: arduino-cli --config-file ${{ matrix.config }} --library ./src/ compile --fqbn esp32:esp32:esp32 ./examples/Client/Client.ino

      - name: FetchWebsite
        run: arduino-cli --config-file ${{ matrix.config }} --library ./src/ compile --fqbn esp32:esp32:esp32 ./examples/FetchWebsite/FetchWebsite.ino

  platformio:
    name: "pio:${{ matrix.env }}:${{ matrix.board }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: ci-arduino-2
            board: esp32dev
          - env: ci-arduino-2
            board: esp32-s2-saola-1
          - env: ci-arduino-2
            board: esp32-s3-devkitc-1
          - env: ci-arduino-2
            board: esp32-c3-devkitc-02

          - env: ci-arduino-3
            board: esp32dev
          - env: ci-arduino-3
            board: esp32-s2-saola-1
          - env: ci-arduino-3
            board: esp32-s3-devkitc-1
          - env: ci-arduino-3
            board: esp32-c3-devkitc-02
          - env: ci-arduino-3
            board: esp32-c6-devkitc-1

          - env: ci-arduino-3-latest
            board: esp32dev
          - env: ci-arduino-3-latest
            board: esp32-s2-saola-1
          - env: ci-arduino-3-latest
            board: esp32-s3-devkitc-1
          - env: ci-arduino-3-latest
            board: esp32-c3-devkitc-02
          - env: ci-arduino-3-latest
            board: esp32-c6-devkitc-1

          - env: ci-arduino-libretiny
            board: generic-bk7231n-qfn32-tuya
          - env: ci-arduino-libretiny
            board: generic-rtl8710bn-2mb-788k

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio
          path: |
            ~/.cache/pip
            ~/.platformio

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - run: PLATFORMIO_SRC_DIR=examples/Client PIO_BOARD=${{ matrix.board }} pio run -e ${{ matrix.env }}
      - run: PLATFORMIO_SRC_DIR=examples/FetchWebsite PIO_BOARD=${{ matrix.board }} pio run -e ${{ matrix.env }}

  esp-idf:
    name: Build with ESP-IDF ${{ matrix.idf_ver }} for ${{ matrix.idf_target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # The version names here correspond to the versions of espressif/idf Docker image.
        # See https://hub.docker.com/r/espressif/idf/tags and
        # https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-docker-image.html
        # for details.
        idf_ver: ["release-v5.4"]
        idf_target:
          [
            "esp32",
            "esp32s2",
            "esp32s3",
            "esp32c2",
            "esp32c3",
            "esp32c6",
            # "esp32h2",
            "esp32p4"
          ]
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: components/asynctcp

      - name: Build
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          idf.py -C ./components/asynctcp/idf_component_examples/client -DEXTRA_COMPONENT_DIRS=$PWD/components build
